### ISSUE TITLE
关于五四制地区选手的年级显示问题

### ISSUE THREAD

**Issue by AtomAlpaca** [OIerDb-ng/OIerDb#10]
## 我发现了以下问题
我是一名哈尔滨市的OIer，现在初四。因为哈尔滨目前实施的是`五四制`而不是`六三制`，因此这里的`初四`实际上对应六三制地区的`初三`，也就是`九年级`。
近日我在 `OIerDb-ng` 查询[自己的成绩](https://oier.baoshuo.dev/oier/128063)时，发现自己目前的年级`初四`被错误地写作`高一`，而奖项中则写作了`初三`。
![Screenshot 2022-01-01 at 12-19-55 OIerDb NG](https://user-images.githubusercontent.com/66774326/147843905-97274137-9849-4457-8e1b-769a8de210d4.png)
我认为这个问题是由于OIerDb使用 [OIerDb-ng/OIerDb-data-generator/oier.py](https://github.com/OIerDb-ng/OIerDb-data-generator/blob/1b35ff032b7a324db78942225e3a6bbb28d93675/oier.py) 处理初中入学年份，再由前端通过与当前年份作差判断选手的年级导致的。
比如我的初中入学年份是2018年，与当前年份2022作差会得出我距离初中入学已经过去了四年，因此得出了我在上高一的错误结论。实际上，我2018年初中入学后上的是`六年级`，相当于六三制小学的最后一年。如果按照六三制，我其实应当算作2019年入学。
## 我认为这些问题可以这样解决
在处理选手信息的时候，根据选手信息的来源地对五四制地区的选手进行特殊处理，使其初中入学年份与对应的六三制初中入学年份相同。
目前我知道的采取五四制的地区有上海市、山东省部分地区和哈尔滨市。

顺颂新祺

**Comment by Menci** [comment]
山东省也不算是五四，我在临沂就是六三

**Comment by nocrizwang** [comment]
直接显示原始数据最好。

**Comment by YOYO-UIAT** [comment]
我是山东六三制学生，现在初三，但网站里面显示高一……

**Comment by renbaoshuo** [comment]
> 我是山东六三制学生，现在初三，但网站里面显示高一……

@YOYO-UIAT 此问题已在 e305d1391b20ebac723634de922df6d68feae2a4 中修复。

**Comment by AtomAlpaca** [comment]
在[`e305d13`](https://github.com/OIerDb-ng/OIerDb/commit/e305d1391b20ebac723634de922df6d68feae2a4)更新后，该问题已经得到解决
![Screenshot_2022-01-17-19-26-57-23~2](https://user-images.githubusercontent.com/66774326/149762142-458166e9-037d-42f7-b4e5-5fd4f20582e3.png)
