### ISSUE TITLE
建议将“NOI D类”改为“NOI 夏令营”

### ISSUE THREAD

**Issue by adfhkjafsdk** [OIerDb-ng/OIerDb#101]
### 需求

NOI 官网的名单公示把 D、E 类统称“夏令营”（不清楚 C 类有没有），在 OIerDb 上都显示成了“NOI D类”，建议修改。

**Comment by StudyingFather** [comment]
同意。

在之前 NOI 夏令营只有 D 类选手，将 NOI 夏令营和 D 类划等号是没有问题的。

考虑到 2019 年之后夏令营增加了 E 类选手（初中生），再以 D 类选手代指夏令营选手感觉确实有以偏概全之嫌，将 D 类改为夏令营能有效反映这一变化，用词也更加准确。

> 不清楚 C 类有没有

C 类名额是正式名额，按正式选手身份参与评奖，不属于夏令营的范畴中。

**Comment by renbaoshuo** [comment]
根据目前的分类规则，D 类的用词确有不妥，我会择机更正这个问题。感谢二位的指正。
