### ISSUE TITLE
建议春季测试获奖名单合并CCF2次公布的名单

### ISSUE THREAD

**Issue by Minecrafl** [OIerDb-ng/OIerDb#111]
### 需求

RT

**Comment by renbaoshuo** [comment]
引用一下本人在 3 月 31 日时的发言：

合并后会出现初中生显示有奖但实际上未获奖的情况，因此不考虑合并。

**Comment by Minecrafl** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
