### ISSUE TITLE
初中生上报NOIP奖项

### ISSUE THREAD

**Issue by JiZiQian** [OIerDb-ng/OIerDb#118]
### 背景

作为一个初二OIer，我希望我的NOIP等比赛的成绩被记录

### 需求

添加一个内容修订功能，使得选手可以通过提交身份证号和成绩证明的方式添加或修改成绩记录

**Comment by CodingOIer** [comment]
NOIp 初中生的成绩无从考证，在各种公开渠道均无法查证

**Comment by renbaoshuo** [comment]
根据 CCF 的规定，NOIP 参赛资格仅限于 **在籍在校的高中生**，故初中生理论上不应作为正式选手参加 NOIP，所获成绩也是不受官方认可的。

https://www.noi.cn/xw/2024-10-10/830958.shtml
