### ISSUE TITLE
毕业年数不一致

### ISSUE THREAD

**Issue by Anguei** [OIerDb-ng/OIerDb#119]
### 问题描述

搜索 noi 2004 部分选手，显示毕业 30 年。

### 预期行为

或应显示「十年以上」

### 复现步骤

搜索 noi2004 等老选手

### 您使用的系统名称及版本

Ubuntu 18.04

### 您使用的浏览器名称及版本

Chrome v123.0

### OIerDb NG 版本

3ea0933

**Comment by yhx-12243** [comment]
Duplicate OIerDb-ng/OIerDb-data-generator#142.
