### ISSUE TITLE
名字缩写功能有bug

### ISSUE THREAD

**Issue by Shyanko** [OIerDb-ng/OIerDb#121]
### 问题描述

搜索 “oyds” 无结果，但是搜索 ”欧阳达晟“ 有结果

### 预期行为

搜索 oyds 有结果 欧阳达晟

### 复现步骤

搜索 oyds

### 屏幕截图

![屏幕截图 2024-11-08 202237](https://github.com/user-attachments/assets/5e323b36-6e66-44f4-989b-168419e1d65b)
![屏幕截图 2024-11-08 202256](https://github.com/user-attachments/assets/17a87ab1-df58-477b-a8a8-d470c64f4e63)

### 您使用的系统名称及版本

Windows 11

### 您使用的浏览器名称及版本

Chrome

### 您的地理位置

湖北省武汉市

### OIerDb NG 版本

5eea2ae

**Comment by Shyanko** [comment]
多音字，oydc就找到了

**Comment by yhx-12243** [comment]
对，晟 是多音字 而且该字在姓名中读音为 chéng 和 shèng 都是常见用法，所以可能会考虑在数据库内更新。
