### ISSUE TITLE
[Bug] 小学选手的年级显示问题

### ISSUE THREAD

**Issue by tzcawa** [OIerDb-ng/OIerDb#15]
RT，小学的巨佬选手会被显示成高中毕业的。

**Comment by renbaoshuo** [comment]
请问能否提供下示例？

**Comment by yhx-12243** [comment]
Fixed in https://github.com/OIerDb-ng/OIerDb-data-generator/commit/b8636185ac77b87d7a6a4bab178e32ae08cf11f7 。
