### ISSUE TITLE
[BUG] 高级搜索界面错误的“高中毕业”时间

### ISSUE THREAD

**Issue by huaruoji** [OIerDb-ng/OIerDb#44]
![image](https://user-images.githubusercontent.com/79401001/200540734-f1477413-bfac-45a5-b666-20f88ca7274b.png)

上图中高中毕业 19 年和高中毕业 23 年的选手实际上分别应该是毕业 9 年和毕业 13 年：

![image](https://user-images.githubusercontent.com/79401001/200540798-f0a3b37c-5cb0-4c6b-befb-8c471e55700c.png)

![image](https://user-images.githubusercontent.com/79401001/200540949-32b32b87-e648-42c8-b6d9-8a4d19e7d26e.png)

![image](https://user-images.githubusercontent.com/79401001/200541003-94a644f0-72ac-4d05-98a3-4512d964b84c.png)

![image](https://user-images.githubusercontent.com/79401001/200541023-1a26d19c-75e2-493c-97fc-cf55ec47a0ad.png)

并不知道是什么原因。

**Comment by renbaoshuo** [comment]
「获奖信息」中的「年级」一栏显示的是参赛时的年级信息。
