### ISSUE TITLE
雅礼中学吞并全国

### ISSUE THREAD

**Issue by Minecrafl** [OIerDb-ng/OIerDb#60]
### 问题描述

https://oier.baoshuo.dev/school/0
本人这边显示有误，全国所有OIer都到这所学校了

### 预期行为

正常显示

### 复现步骤

访问
https://oier.baoshuo.dev/school/0

### 您使用的系统名称及版本

WIN 10

### 您使用的浏览器名称及版本

chrome

### OIerDb NG 版本

c81d468

**Comment by purple-vine** [comment]
太离谱，今晚九点还没事，<del>刚才一看我就到雅礼了</del>

**Comment by renbaoshuo** [comment]
我的锅我的锅，生病把我搞迷糊了，昨晚上鱼大已经 revert 掉了那个有锅的 commit https://github.com/OIerDb-ng/OIerDb-data-generator/commit/fa07ad3d3cbf0e960ff0376396e9c20801b9ddcc
